title: Blog with Github Pages
author: SudoMishra
email: sudhanshu.ktj@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Learning how to blog using Github Pages

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
